In [ ]:
#Using numpy functions 

In [3]:
import numpy as np


# 1. Creating a NumPy array using np.array()
a = np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [6]:
# 3. Creating a 3x3 Identity Matrix using np.eye()
imatrix = np.eye(3) 
print(imatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# 3. Creating a  evenly spaced numbers using np.linspace()
lspace = np.linspace(0, 20,5)
print(lspace)

[ 0.  5. 10. 15. 20.]


In [14]:
# 4. Creating a range of numbers using np.arange()
arange = np.arange(0, 24, 4) 
print(arange)

[ 0  4  8 12 16 20]


In [ ]:
# 5. Creating an array of zeros using np.zeros()
zero = np.zeros((4, 4))  # 4x4 matrix 
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# 6. Creating an array of ones using np.ones()
ones_arr = np.ones((6, 5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 7. Creating an array filled with a constant value using np.full()
six_arr = np.full((6, 6), 5) 
print(six_arr)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [19]:
# 8.producing Random numbers using np.random.rand()
rand_arr = np.random.rand(3, 3)
print(rand_arr)


[[0.31695179 0.45624304 0.62338613]
 [0.37565923 0.76278204 0.57948302]
 [0.6775645  0.25939361 0.25581715]]


In [21]:
# 9. Random integers using np.random.randint()
rand_int = np.random.randint(1, 100, size=(3, 3))  
print(rand_int)

[[83 72 52]
 [76 53 75]
 [98 87 19]]


In [22]:
# 10. Create indices grid using np.indices()
ind = np.indices((3, 3)) 
print(ind)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [24]:
# 11. Check array attributes (ndim, size, shape)
print("\nArray Attributes:")
print("ndim (number of dimensions):", a.ndim)
print("size (total number of elements):", a.size)
print("shape (rows, columns):", a.shape)



Array Attributes:
ndim (number of dimensions): 1
size (total number of elements): 5
shape (rows, columns): (5,)


In [28]:
# 12. Reshape an array using np.reshape()
reshaped = np.arange(12).reshape(6,2) 
print(reshaped)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [29]:
# 13. Transpose of a matrix using np.transpose()
transposed = reshaped.T
print(transposed)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [30]:
# 14. Mathematical operations
math_arr = np.array([10, 20, 30, 40, 50])
print("\nSum:", np.sum(math_arr))
print("Mean:", np.mean(math_arr))
print("Max:", np.max(math_arr))
print("Min:", np.min(math_arr))
print("Standard Deviation:", np.std(math_arr))


Sum: 150
Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951


In [7]:
# 15. Creating diagonal matrix using np.diag()
diag_arr = np.diag([10,10,10,10])
print(diag_arr)

[[10  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 10]]


In [34]:
# 16. Flattening array using np.ravel()
flat = reshaped.ravel()
print(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
# 17. Sorting array using np.sort()
unsorted = np.array([60, 100, 550, 20, 440])
sorted_arr = np.sort(unsorted)
print(sorted_arr)

[ 20  60 100 440 550]


In [4]:
# 18. Unique values using np.unique()
dup_arr = np.array([1, 2, 2, 3, 4, 4, 5,6,4,3,5,9,6])
unique_vals = np.unique(dup_arr)
print(unique_vals)

[1 2 3 4 5 6 9]
